### ISSUE TITLE
Retrieving colorScheme

### ISSUE THREAD

**Issue by carekb684** [bernaferrari/RandomColorScheme#3]
Hello!

Thanks for this plugin.

It would be cool if there was a feature where the seed number was printed when hot reloading / starting the app, or perhaps some way to get the colors used.

When trying different themes there seems to be no way to then start using the one you found and like.

Thanks again.

**Comment by bernaferrari** [comment]
Well. It is supposed to print the full ColorScheme on every call. Isn’t it doing that?

**Comment by carekb684** [comment]
Ah sorry i completely missed it! The seed number would be nice as well though.

Thanks

**Comment by bernaferrari** [comment]
I don’t have it. I just call math.Random() without any parameter. I could generate a random number to pass into the random number generator, but what if I update the library tomorrow? These methods are ultra-sensitive. If someone asks for secondaryVariant, error or onSurface colors, everything is going to change. The nice thing is that you can provide the seed with a button to increment it, just like I did on the sample.

**Comment by carekb684** [comment]
Yes, i just realized i can generate my own seed and print it. Of course 👍 
Thanks again for the plugin
