### ISSUE TITLE
Add secondaryVariant generation

### ISSUE THREAD

**Issue by timekone** [bernaferrari/RandomColorScheme#5]
Hi! 

Thank you for an awesome package!

Could you please add [secondaryVariant](https://api.flutter.dev/flutter/material/ColorScheme/secondaryVariant.html) generation as well?

Maybe it should have the same logic as primaryVariant generation, `primaryLightness - 10.0`?

https://github.com/bernaferrari/RandomColorScheme/blob/39c64c5e4c8329921d0cb4d0186dc6d98c09f064/lib/random_color_scheme.dart#L213-L217

Should I make a pull request?

**Comment by bernaferrari** [comment]
Sorry, I forgot!
Already pushed, you can update to 0.1.3!
Thanks for the idea!
